config: # This is file 'patch/kernel/archive/meson64-6.4/0000.patching_config.yaml'

  # Just some info stuff; not used by the patching scripts
  name: rockchip-rk3588-collabora
  kind: kernel
  type: mainline # or: vendor
  branch: linux-6.4.y
  last-known-good-tag: v6.4
  maintainers:
    - { github: rpardini, name: Ricardo Pardini, email: ricardo@pardini.net, armbian-forum: rpardini }

  # .dts files in these directories will be copied as-is to the build tree; later ones overwrite earlier ones.
  # This is meant to provide a way to "add a board DTS" without having to null-patch them in.
  dts-directories:
    - { source: "dt", target: "arch/arm64/boot/dts/rockchip" }

  # every file in these directories will be copied as-is to the build tree; later ones overwrite earlier ones
  # This is meant as a way to have overlays, bare, in a directory, without having to null-patch them in.
  # @TODO need a solution to auto-Makefile the overlays as well
  overlay-directories:
    - { source: "overlay", target: "arch/arm64/boot/dts/rockchip/overlay" }

  # the Makefile in each of these directories will be magically patched to include the dts files copied
  #  or patched-in; overlay subdir will be included "-y" if it exists.
  # No more Makefile patching needed, yay!
  auto-patch-dt-makefile:
    - { directory: "arch/arm64/boot/dts/rockchip", config-var: "CONFIG_ARCH_ROCKCHIP" }

  # configuration for when applying patches to git / auto-rewriting patches (development cycle helpers)
  patches-to-git:
    do-not-commit-files:
      - "MAINTAINERS" # constant churn, drop them. sorry.
      - "Documentation/devicetree/bindings/arm/rockchip.yaml" # constant churn, conflicts on every bump, drop it. sorry.
    do-not-commit-regexes: # Python-style regexes
      - "^arch/([a-zA-Z0-9]+)/boot/dts/([a-zA-Z0-9]+)/Makefile$" # ignore DT Makefile patches, we've an auto-patcher now

