config: # This is file 'patch/kernel/archive/sm8250-6.7/0000.patching_config.yaml'

  # Just some info stuff; not used by the patching scripts
  name: sm8250-6.10
  kind: kernel
  type: mainline # or: vendor
  branch: linux-6.10.y
  last-known-good-tag: v6.10-rc2
  maintainers:
    - { github: rpardini, name: Ricardo Pardini, email: ricardo@pardini.net, armbian-forum: rpardini }

  # .dts files in these directories will be copied as-is to the build tree; later ones overwrite earlier ones.
  # This is meant to provide a way to "add a board DTS" without having to null-patch them in.
  dts-directories:
    - { source: "dt", target: "arch/arm64/boot/dts/qcom" }

  # the Makefile in each of these directories will be magically patched to include the dts files copied
  #  or patched-in; overlay subdir will be included "-y" if it exists.
  # No more Makefile patching needed, yay!
  auto-patch-dt-makefile:
    - { directory: "arch/arm64/boot/dts/qcom", config-var: "CONFIG_ARCH_QCOM" }

  # configuration for when applying patches to git / auto-rewriting patches (development cycle helpers)
  patches-to-git:
    do-not-commit-files:
      - "MAINTAINERS" # constant churn, drop them. sorry.
    do-not-commit-regexes: # Python-style regexes
      - "^arch/([a-zA-Z0-9]+)/boot/dts/([a-zA-Z0-9]+)/Makefile$" # ignore DT Makefile patches, we've an auto-patcher now

