config:

  # Board-specific overlays live inside this directory to keep Helios64
  # patches self contained.
  overlay-directories:
    - { source: "defconfig", target: "configs" }
    - { source: "dt_upstream_rockchip", target: "dts/upstream/src/arm64/rockchip" }
    - { source: "dt_uboot", target: "arch/arm/dts" }
    - { source: "board", target: "board/kobol/helios64" }
    - { source: "include_configs", target: "include/configs" }
