# Target file for all kernel artifacts across all non-eos boards.

targets:
  all-kernels:
    pipeline:
      only-artifacts: [ "kernel" ]
    vars:
      BUILD_MINIMAL: "yes"
      BUILD_DESKTOP: "no"
      RELEASE: "sid"
    items-from-inventory:
      not-eos: yes # not-eos boards, all branches
