name: Docker build tests
# This workflow is triggered 1st, 16th and 31st
on:
  schedule:
    - cron: '0 0 */15 * *'
jobs:
  build_on_focal:
    name: "PUB: sunxi u-boot Docker Focal"
    runs-on: ubuntu-20.04
    steps:
     - uses: actions/checkout@v1
     - name: Login to DockerHub Registry
       run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin 
     - name: Build Docker image
       shell: bash {0}
       run: |
        sed -i "s/-it --rm/-i --rm/" config/templates/config-docker.conf
        touch .ignore_changes
        ./compile.sh docker KERNEL_ONLY="yes" BOARD="bananapi" BRANCH="current" KERNEL_CONFIGURE="no" USE_TORRENT="yes" REPOSITORY_INSTALL="kernel"
        docker tag armbian:$(cat VERSION) armbian/build:latest
     - name: Push Docker image
       run: docker push armbian/build:latest
