name: Build Desktops at PR
#
# Generates supported desktops for uefi-arm64, uefi-x86 and rpi4 if label "Desktop" is set
#

on:
  schedule:
    - cron: "30 17 * * *"
  workflow_dispatch:

  pull_request:
    types: [ready_for_review]

  pull_request_review:
    types: [submitted]

permissions:
  contents: read

jobs:

  Maintain:

    permissions:
      contents: none

    if: ${{ (github.repository_owner == 'Armbian') && (contains( github.event.pull_request.labels.*.name, 'Desktop :desktop_computer:') || github.event_name == 'workflow_dispatch') }}
    uses: armbian/scripts/.github/workflows/build-test-image-docker.yml@master

    with:

      runner: "ubuntu-latest"
      reference: ${{ github.event.pull_request.head.sha }}
