name: Build everything
on:
  pull_request:
jobs:
  build:
    name: Compile changed kernels
    runs-on: [self-hosted,public]
    steps:
      - name: Run compilation to see if it breaks something
        shell: bash         
        run: |  
         cd build
         ./compile.sh all KERNEL_ONLY="yes" BETA="no"
