name: Build Docker hub image
# This workflow is triggered 1st, 16th and 31st
on:

  schedule:
    - cron: '0 0 */15 * *'

jobs:

  build:

    name: "Build Docker image"
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'Armbian' }}
    steps:

     - uses: actions/checkout@v1

     - name: Login to DockerHub Registry
       run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin 

     - name: Build Docker image
       shell: bash {0}
       run: |
        sed -i "s/-it --rm/-i --rm/" config/templates/config-docker.conf
        touch .ignore_changes
        ./compile.sh docker KERNEL_ONLY="yes" BOARD="bananapi" BRANCH="current" KERNEL_CONFIGURE="no" USE_TORRENT="yes" REPOSITORY_INSTALL="kernel"
        docker tag armbian:$(cat VERSION) armbian/build:latest

     - name: Push Docker image
       run: docker push armbian/build:latest
