name: Forked Helper

on:
  push:
  release:
  deployment:
  pull_request:
  workflow_dispatch:

jobs:
  fork-repository-dispatch:
    name: ğŸ“¢ Run repository dispatch to default fork branch
    if: ${{ github.repository_owner != 'armbian' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch event on forked repostitory
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ARMBIAN_SELF_DISPATCH_TOKEN }}
          repository: ${{ github.repository }}
          event-type: armbian
          client-payload: >
            {
              "event": "${{ github.event_name }}",
              "ref": "${{ github.ref }}",
              "base_ref": "${{ github.base_ref }}",
              "sha": "${{ github.sha }}",
              "event_details": ${{ toJson(github.event) }}
            }
