name: Forked helper

on:
  push:
  release:
  deployment:
  pull_request:
  workflow_dispatch:

jobs:
  fork-repository-dispatch:
    name: ğŸ“¢ Run repository dispatch to default fork branch
    if: ${{ github.repository_owner != 'armbian' }}
    runs-on: ubuntu-latest
    steps:
      - name: Assign secret
        id: get_dispatch_secret
        run: echo '::set-output name=dispatch_secret::${{ secrets.ARMBIAN_SELF_DISPATCH_TOKEN }}'
      - name: Get event details
        id: get_event_details
        run: |
          JSON=$(cat ${{ github.event_path }})
          JSON="${JSON//'%'/'%25'}"
          JSON="${JSON//$'\n'/'%0A'}"
          JSON="${JSON//$'\r'/'%0D'}"
          echo "::set-output name=event_details::${JSON}"
      - name: Debug details
        uses: hmarr/debug-action@v2
      - name: Dispatch event on forked repostitory
        if: steps.get_dispatch_secret.outputs.dispatch_secret
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ steps.get_dispatch_secret.outputs.dispatch_secret }}
          repository: ${{ github.repository }}
          event-type: armbian
          client-payload: >
            {
              "event": "${{ github.event_name }}",
              "ref": "${{ github.ref }}",
              "base_ref": "${{ github.base_ref }}",
              "sha": "${{ github.sha }}",
              "event_details": ${{ steps.get_event_details.outputs.event_details }}
            }
