name: "Maintenance: Welcome first-time PR contributor"

on:
  pull_request_target:
    types: opened

jobs:
  welcome-first-time-contributor:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: plbstl/first-contribution@v4
        with:
          pr-opened-msg: |
            ### Hey @{fc-author}! ğŸ‘‹

            Thanks for submitting your first pull request to the Armbian project â€” we're excited to have you contributing! ğŸ§¡  
            Your effort doesnâ€™t just improve Armbian â€” it benefits the entire community of users and developers.

            If you'd like to stay informed about project updates or collaborate more closely with the team,  
            you can optionally share some personal contact preferences at [armbian.com/update-data](https://www.armbian.com/update-data/).  
            This helps us keep in touch without relying solely on GitHub notifications.

            Also, donâ€™t forget to â­ star the repo if you havenâ€™t already â€” and welcome aboard! ğŸš€
