name: "Maintenance: Welcome first-time issue contributor"

on:
  issues:
    types: opened

permissions:
  contents: read

jobs:
  welcome-first-time-contributor:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: plbstl/first-contribution@v4
        with:
          labels: "Good first issue"
          issue-opened-msg: |
            ### Hey @{fc-author}! ğŸ‘‹

            Thanks for opening your first issue with the Armbian project â€” weâ€™re glad to have you here! ğŸ§¡  
            Your input doesnâ€™t just help us improve the project â€” it benefits everyone who uses Armbian.

            If you'd like to stay informed about project updates or collaborate more closely with the team,  
            you can optionally share some personal contact preferences at [armbian.com/update-data](https://www.armbian.com/update-data/).  
            This helps us keep in touch without relying solely on GitHub notifications.

            Also, donâ€™t forget to â­ star the repo to support the work â€” and welcome aboard! ğŸš€
