name: "Maintenance: Announce merge"

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  announcepush:
    # Do not run this workflow in forks
    if: ${{ github.repository == 'armbian/build' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Send push to Discord
        run: |
          curl -i -H "Accept: application/json" -H "Content-Type: application/json" -X POST --data \
          "{\"username\": \"Github\", \"avatar_url\": \"${{ secrets.AVATARURL }}\", \"content\": \"\
          :white_check_mark: **Merged** into [$GITHUB_REPOSITORY](<$GITHUB_SERVER_URL/$GITHUB_REPOSITORY>) by [$GITHUB_ACTOR](<$GITHUB_SERVER_URL/$GITHUB_ACTOR>) - \
          [Link](<$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/commit/$GITHUB_SHA>): *$(git show -s --format=%s)*\"}" ${{ secrets.WEBHOOKURL }}
