name: "Maintenance: Listen PR review"
on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: read

jobs:
  ping:
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Save PR number
        run: echo "${{ github.event.pull_request.number }}" > pr.txt

      - uses: actions/upload-artifact@v6.0.0
        with:
          # unique name: includes workflow run id
          name: pr-number-${{ github.run_id }}
          path: pr.txt
