name: Coding style check

on:
  pull_request:
    types: [opened, reopened, edited, synchronize, review_requested]
    paths:
      - lib/**
      - packages/**
      - extensions/**
      - tools/**
      - .github/workflows/*

concurrency:
  group: coding-style-${{github.event.pull_request.number}}
  cancel-in-progress: true

jobs:
  editorconfig:
    name: "Coding style check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker
