name: Pull Request Labeling

on:
  - pull_request

jobs:

  size-label:
    permissions:
      contents: read  # to determine modified files
      pull-requests: write  # to add labels to PRs
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@v0.5.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          sizes: >
            {
              "0": "small",
              "50": "medium",
              "250": "large"
            }
