name: Smoke tests on DUTs
#
# Runs varios tests with latest nighly codebase on a real hardware
#

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build train"]
    types:
      - completed

permissions:
  contents: read

jobs:

  Smoke:
    permissions:
      contents: none

    if: ${{ github.repository_owner == 'Armbian' }}
    uses: armbian/scripts/.github/workflows/smoke-tests.yml@master
    secrets:
      KEY_CI: ${{ secrets.KEY_CI }}
      KEY_POWER_ON: ${{ secrets.KEY_POWER_ON }}
      USER_REPOSITORY: ${{ secrets.USER_REPOSITORY }}
      HOST_REPOSITORY: ${{ secrets.HOST_REPOSITORY }}
      KNOWN_HOSTS_REPOSITORY: ${{ secrets.KNOWN_HOSTS_REPOSITORY }}
