name: Update Docker
#
# Update Docker images we use for building CI
#

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 0'
  
  # automatically rebuild docker images when VERSION is changed on master branch
  push:
    branches:
      - master
    paths:
      - 'VERSION'

permissions:
  contents: read

jobs:

  Docker:
    permissions:
      contents: none

    if: ${{ github.repository_owner == 'Armbian' }}
    uses: armbian/scripts/.github/workflows/update-docker-image.yml@master

    secrets:
      CR_PAT: ${{ secrets.CR_PAT }}

  Docker-test:
    permissions:
      contents: none

    needs: Docker
    if: ${{ github.repository_owner == 'Armbian' }}
    uses: armbian/scripts/.github/workflows/build-test-image-docker.yml@master
    with:

      runner: "ubuntu-latest"
      reference: master
